language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t akakafonis/docker-react -f Dockerfile.dev .

script:
    #test command should force Jest to run in CI-mode and tests to be run once instead of launching the watcher
  - docker run -e CI=true akakafonis/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "eu-west-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-west-2-506772638431"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY