sudo: required
services:
    - docker

before_install:
    -docker build -t akakafonis/docker-react -f Dockerfile.dev .

script:
    #-- --coverage forces test suite to exit automatically as soon as first run is completed
    - docker run akakafonis/docker-react npm run test -- --coverage