language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t akakafonis/docker-react -f Dockerfile.dev .

script:
    #test command should force Jest to run in CI-mode and tests to be run once instead of launching the watcher
  - docker run -e CI=true akakafonis/docker-react npm run test